### ISSUE TITLE
Expand Sch H extract: I. Part III - Bad debt and Medicare

### ISSUE THREAD

**Issue by rbookman** [jherr/get-donations#4]
Create a new section to pull more data from the return.
Also, it would be nice if we could make it easy to elect which (1 or more) part(s) of Sch H to extract....

Here, I want to start by getting the data from Part III of Schedule H, lines 1-8.
Only lines 2-7 are $'s.
Others are yes/no (line 1) or checkbox (line 8)

![image](https://user-images.githubusercontent.com/2439508/146275933-12ad6f58-b5a4-4577-a7b1-566e5f9ff06d.png)

**Comment by rbookman** [comment]
More complete image:
<img width="1568" alt="image" src="https://user-images.githubusercontent.com/2439508/146276465-d034f0f2-2d06-439c-8148-360df062aa6f.png">

**Comment by jherr** [comment]
Added everything except item 8. Could add that but it would be a different mechanism and we should talk about how we want to express that as a value. If we want to handle that we can create another issue to support it.
